/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { OrdersService } from "../orders.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OrdersCreateInput } from "./OrdersCreateInput";
import { OrdersWhereInput } from "./OrdersWhereInput";
import { OrdersWhereUniqueInput } from "./OrdersWhereUniqueInput";
import { OrdersFindManyArgs } from "./OrdersFindManyArgs";
import { OrdersUpdateInput } from "./OrdersUpdateInput";
import { Orders } from "./Orders";
import { FoodMenuFindManyArgs } from "../../foodMenu/base/FoodMenuFindManyArgs";
import { FoodMenu } from "../../foodMenu/base/FoodMenu";
import { FoodMenuWhereUniqueInput } from "../../foodMenu/base/FoodMenuWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class OrdersControllerBase {
  constructor(
    protected readonly service: OrdersService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Orders })
  @nestAccessControl.UseRoles({
    resource: "Orders",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: OrdersCreateInput): Promise<Orders> {
    return await this.service.create({
      data: {
        ...data,

        users: {
          connect: data.users,
        },
      },
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Orders] })
  @ApiNestedQuery(OrdersFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Orders",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Orders[]> {
    const args = plainToClass(OrdersFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Orders })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Orders",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: OrdersWhereUniqueInput
  ): Promise<Orders | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Orders })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Orders",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: OrdersWhereUniqueInput,
    @common.Body() data: OrdersUpdateInput
  ): Promise<Orders | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          users: {
            connect: data.users,
          },
        },
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,

          users: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Orders })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Orders",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: OrdersWhereUniqueInput
  ): Promise<Orders | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,

          users: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/foodMenus")
  @ApiNestedQuery(FoodMenuFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FoodMenu",
    action: "read",
    possession: "any",
  })
  async findManyFoodMenus(
    @common.Req() request: Request,
    @common.Param() params: OrdersWhereUniqueInput
  ): Promise<FoodMenu[]> {
    const query = plainToClass(FoodMenuFindManyArgs, request.query);
    const results = await this.service.findFoodMenus(params.id, {
      ...query,
      select: {
        category: true,
        createdAt: true,
        discount: true,
        foodDesc: true,
        foodImage: true,
        foodName: true,
        id: true,
        price: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/foodMenus")
  @nestAccessControl.UseRoles({
    resource: "Orders",
    action: "update",
    possession: "any",
  })
  async connectFoodMenus(
    @common.Param() params: OrdersWhereUniqueInput,
    @common.Body() body: FoodMenuWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      foodMenus: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/foodMenus")
  @nestAccessControl.UseRoles({
    resource: "Orders",
    action: "update",
    possession: "any",
  })
  async updateFoodMenus(
    @common.Param() params: OrdersWhereUniqueInput,
    @common.Body() body: FoodMenuWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      foodMenus: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/foodMenus")
  @nestAccessControl.UseRoles({
    resource: "Orders",
    action: "update",
    possession: "any",
  })
  async disconnectFoodMenus(
    @common.Param() params: OrdersWhereUniqueInput,
    @common.Body() body: FoodMenuWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      foodMenus: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
